### PR TITLE
Zgl comments

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**
# Description
Add description about what this pull request covers.
- Added better comments for the Order and Category models and serializers, fixed the spacing on serializers and added some methods
## Number of Fixes
Type of number of fixes included in this PR.

## Related Ticket(s)
List related ticket(s) that apply to the work done in this pull request

## Problem to Solve
Describe the problem(s) this pull request solves.
- Needs better docs and comments
## Proposed Changes
Describe the proposed changes.
- just adding more methods and comments on the serializer and models
## Expected Behavior
Describe the expected behavior.
-Everything should work normally
## Steps to Test Solution

1. pull down
1. migrate
1. runserver

## Testing

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

## Documentation
[ ] There is new documentation in this pull request that must be reviewed..
[ X] I added documentation for any new classes/methods

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

### CODE REVIEW

**Comment by sales-ls21** [comment]
Couple of places on serializers.py where you have a name mix-up, but otherwise working well.

**Comment by nathantbaker** [comment]
+1 on wrong author in serializer. I tested API functionality and everything still works. Just needs that tweak.

**Comment by ZoeLeBlanc** [comment]
fixed serializer name now. Thanks for catching that!

**Comment by nathantbaker** [comment]
👍

**Comment by sales-ls21** [comment]
:+1:  Good on the name change.

**Pull request merged**
